services:
  - type: web
    name: mapa-prilezitosti
    env: python
    plan: free
    buildCommand: ./deploy/build.sh
    startCommand: uvicorn api.server_full:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
      - key: TRADE_UNITS_SCALE
        value: "1000"