services:
  # Backend API service
  - type: web
    name: mapa-prilezitosti-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements-deployment.txt
    startCommand: uvicorn api.server_full:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TRADE_UNITS_SCALE
        value: "1000"
      - key: PORT
        value: "8000"

  # Frontend static site  
  - type: web
    name: mapa-prilezitosti-ui
    env: static
    buildCommand: npm install --prefix ui && npm run build --prefix ui
    staticPublishPath: ui/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: VITE_API_BASE
        value: https://mapa-prilezitosti-api.onrender.com