#!/bin/bash
# ============================================================================
# release-serving — package data/serving/ and publish it as a GitHub Release
# asset the deploy can download (M7).
#
# The serving layer (~43 MB, gitignored) is machine-generated by
# rebuild-all.command / etl/07. It is too big to commit and must never drift
# from the ETL, so we ship it out-of-band as a Release asset named
# `serving.tar.gz`, marked --latest. deploy/build.sh pulls
# `releases/latest/download/serving.tar.gz` at deploy time.
#
# Run AFTER rebuild-all.command, from the repo root, with `gh` authenticated
# (needs `repo` scope). Re-running the same day re-uploads (clobbers) the asset.
# ============================================================================
set -euo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$DIR"

SERVING="data/serving"
REQUIRED=(core_trade.parquet signals.parquet peer_groups.parquet hs6_names.parquet countries.parquet)
ASSET="serving.tar.gz"
TAG="serving-$(date +%Y-%m-%d)"

echo "release-serving  (repo: $DIR)"

# --- preconditions -----------------------------------------------------------
if ! command -v gh >/dev/null 2>&1; then
  echo "✗ gh CLI not found. Install it and 'gh auth login' (needs repo scope)."; exit 1
fi
missing=0
for f in "${REQUIRED[@]}"; do
  if [ ! -f "$SERVING/$f" ]; then echo "✗ missing $SERVING/$f"; missing=1; fi
done
if [ "$missing" -ne 0 ]; then
  echo "✗ serving layer incomplete. Run rebuild-all.command first."; exit 1
fi

# --- package -----------------------------------------------------------------
# Tar from INSIDE data/serving so members are bare filenames (no path prefix),
# which build.sh extracts straight into data/serving/. The tarball MUST be named
# exactly `serving.tar.gz` (the asset filename) so the deploy can fetch it via
# releases/latest/download/serving.tar.gz — so build it inside a temp dir under
# that name (the `#label` suffix to `gh release` sets a label, not the filename).
WORKDIR="$(mktemp -d -t serving-release.XXXXXX)"
TARBALL="$WORKDIR/$ASSET"
tar -czf "$TARBALL" -C "$SERVING" "${REQUIRED[@]}"
SIZE=$(du -h "$TARBALL" | cut -f1)
echo "  packaged ${#REQUIRED[@]} parquets → $ASSET ($SIZE)"

# --- publish -----------------------------------------------------------------
NOTES="Serving layer (data/serving/*.parquet) built by rebuild-all.command on $(date +%Y-%m-%d).
Downloaded at deploy time by deploy/build.sh via releases/latest/download/$ASSET."

if gh release view "$TAG" >/dev/null 2>&1; then
  echo "  release $TAG exists → re-uploading asset (clobber)"
  gh release upload "$TAG" "$TARBALL" --clobber
  gh release edit "$TAG" --latest >/dev/null
else
  echo "  creating release $TAG (marked --latest)"
  gh release create "$TAG" "$TARBALL" \
    --title "Serving layer $TAG" \
    --notes "$NOTES" \
    --latest
fi

rm -rf "$WORKDIR"
echo "✅ published. build.sh will fetch:"
echo "   https://github.com/janindracek/mapa-prilezitosti/releases/latest/download/$ASSET"
